In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent=['the glass of  milk', 'the glass of juice','the cup of tea','i am good boy','i am i good developer','understand the meaning of words','your videos are good']

In [3]:
sent

['the glass of  milk',
 'the glass of juice',
 'the cup of tea',
 'i am good boy',
 'i am i good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
# giving vocabolary size
voc_size=10000

In [8]:
# one hot representation
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[8608, 8089, 9431, 2426], [8608, 8089, 9431, 2819], [8608, 9927, 9431, 7066], [1278, 6804, 9707, 1690], [1278, 6804, 1278, 9707, 9860], [7009, 8608, 3681, 9431, 2289], [2841, 4120, 5177, 9707]]


# word embedding representation

In [14]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [15]:
import numpy as np

In [17]:
sent_length=8
embedding_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedding_docs)

[[   0    0    0    0 8608 8089 9431 2426]
 [   0    0    0    0 8608 8089 9431 2819]
 [   0    0    0    0 8608 9927 9431 7066]
 [   0    0    0    0 1278 6804 9707 1690]
 [   0    0    0 1278 6804 1278 9707 9860]
 [   0    0    0 7009 8608 3681 9431 2289]
 [   0    0    0    0 2841 4120 5177 9707]]
